language: node_js
node_js:
- stable
- lts/*
cache: yarn
env:
  global:
  - secure: oxWHymDmKMUNVGxUdAIEVOvs8P64Ey8L3ZgEbaGzmcZmC1/x1DKrDPsIqZIDR3zqhlRHjjpMaOMlL9ZdByHfZ4VZxcurEgvryFFBOlNrBxfNiAD+mLkEgiOhdMULF0VtZmiapVHJ+c6G8EiPDDJPORMUVnbx6EQC/iETQf0nfZtc/SO3859zT2pxC/ll9d3sPDaiJ8TXct8eCwJeuoc9QNxP8rOdIKcKlimsvQlVhMHawUlPg6I8uHSwlBB1Lrb35CPAE1scg4xzVGwaQ531gtJrSLTaGdrVxQdbd6Q6FHSSH8wsdq0T96NdLYT5Mae87+WLSltb8UPL8dOaks+04ji0V8+8ujh6lblR58C0ru1RFsuVyaQkQhPCqw/Um6kghCMNmyPPtFI37ERjV4XZZhzzwddlz/lmbEgkgcQ2nKuX137fYKBIbg0ODc2PQwlrBIEYHOJsdJj0yytuRxwmhY9pko0UVx4j7Ebtm8jQZfyyCbK+d6Y+LW83Bu4HJHHMOOX736EcuFvAIPC4UH0nlkaIx+6LlgVFYNmC9ndAU18l5wbGzUCruyMiBideDGLrFcm1m6yaDhTDbf36vKRYI4JANfEF+jU8cwk/2QVb0mbsjVL5ZCD0gfKXTI0ZNPBlHS1LbCDC9jnrVKI2aZismffS6KH0ProvgkT5oC7u4qY=
before_deploy:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > "${HOME}/.npmrc"
- npm whoami
deploy:
- provider: script
  script: npm run release
  skip_cleanup: true
  on:
    repo: uncovertruth/styleguide
    tags: true
notifications:
  email: false
  slack:
    secure: MZyc+Ff87HJd19Rm5gZFbFE+QEMhpGpZWW9nsmNVkxECTigNH8ElPCHEAWaSGw60IwVuq7NQI+Nd6AakKcV1oqn5SvbFeYKCqzY9toCkjYH003rowPrYeGocjy64u7oBT0nFdZbSwK9o3d64PH/AK3B5PyBRRaPyR+rjZsFDDMBkakaZnnXPUkQReb/gbH7PgOAh0dWrz4Zx1Ib7w7Z0e75L0ouJ9FbaCCC6MV8gzCRweos06shrSWXEouwtpKSSKzcJHMGYfVuV3iHS6UGg+1jBRAy65wmBNPeUXc8VNzJEt3qHZo3LsFh1VRh7lFj4E++/+YWYRa+GqQdTYowMySW5MyiAOYvBCJOn7OOL57oQxaJLZ3EzrGWhzs3PTV2r2C0RSvL5XqrV+FvkQJYTEwqcZ9B5UOzpYt25/FZ7C8zmRlBgOrqO67w7RJ5jcOmT0spKpi/PNTZD9tshccHHVVvenx9pZdtN2G0LEn24DsHKIE8+/UN+cSEJx6JMaYXcHt5kEUwVhm29qv9GUcqVcBTfQ33cll8pG0r3VS3XbpCR/zlfRTljdztbuJu0cnWW7mQgWHR20OE+O/uqexEWnrIFsXhouyi0zdGA9mVmBNvyj7dZbz2F+rIG4n76khJndE2dN4ACMNjU/vGCYyVydAikcX0zNK52GylghXpQFXI=
