language: node_js
node_js:
- stable
- lts/*
cache: yarn
before_deploy:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > "${HOME}/.npmrc"
- npm whoami
deploy:
- provider: script
  script: npm run release
  skip_cleanup: true
  on:
    repo: uncovertruth/styleguide
    tags: true
notifications:
  email: false
  slack:
    secure: MZyc+Ff87HJd19Rm5gZFbFE+QEMhpGpZWW9nsmNVkxECTigNH8ElPCHEAWaSGw60IwVuq7NQI+Nd6AakKcV1oqn5SvbFeYKCqzY9toCkjYH003rowPrYeGocjy64u7oBT0nFdZbSwK9o3d64PH/AK3B5PyBRRaPyR+rjZsFDDMBkakaZnnXPUkQReb/gbH7PgOAh0dWrz4Zx1Ib7w7Z0e75L0ouJ9FbaCCC6MV8gzCRweos06shrSWXEouwtpKSSKzcJHMGYfVuV3iHS6UGg+1jBRAy65wmBNPeUXc8VNzJEt3qHZo3LsFh1VRh7lFj4E++/+YWYRa+GqQdTYowMySW5MyiAOYvBCJOn7OOL57oQxaJLZ3EzrGWhzs3PTV2r2C0RSvL5XqrV+FvkQJYTEwqcZ9B5UOzpYt25/FZ7C8zmRlBgOrqO67w7RJ5jcOmT0spKpi/PNTZD9tshccHHVVvenx9pZdtN2G0LEn24DsHKIE8+/UN+cSEJx6JMaYXcHt5kEUwVhm29qv9GUcqVcBTfQ33cll8pG0r3VS3XbpCR/zlfRTljdztbuJu0cnWW7mQgWHR20OE+O/uqexEWnrIFsXhouyi0zdGA9mVmBNvyj7dZbz2F+rIG4n76khJndE2dN4ACMNjU/vGCYyVydAikcX0zNK52GylghXpQFXI=
env:
  global:
    secure: gv7Q8uKR+6eraSKdrJFiFel5sYcfH8X7+8orleUHjcUdUyOeYmLb50a+0vqWyfpdURn4GzNOy3rNhdRX5kaV5SKMDmatOK10wSRhqz0CMznVbprTpAHlvkC9yJZtcTUdL3U62rDv0cLL/29nnGW/1UAC/3flKlTYYSeQKh3EPTD+J6ZP9h5I8OOZlt23dqRbPrjfN5wbI+4RRlVT8N9Io87/FxCyUVkLOxF4a3UpeY1Mk7X9j467MaxG3Jepkg/JuR8V9irEc4ofGeHVaYNQORo90TR8vpXKFfUkZHuLeiLgTWuQQF2KuNIJny3Mh5qiE5R1nk/TDVakeJeNYcE/UZ3Dh47ywYlliG5PCGx6DHhwnItsYd+KLfL08ZebGEYMvP3UX4JMi/72Ug2sWqnC74xwjlDz264DH9CoQb8tgvA2IfhlJ2XPqk4mvtfklYTNw7dbjdzY01gHVsdSvgS5KKYJSwXGwP7myuUq0hiebqghDTXmZnuffqZQwgoq3kBLvnVn+J2htNzdLnbQb4Gf5Sic+9B0g9+iNEfrEZ/7LaUWQXRLH1fnf2ub3Ih3oQ6kewPjC7YI9ABizoI1UDhDtfkffYjJhD+xQClEQ3OB2fXt677v3xCVbHKf13u03wcdS8XSQH3ICKyzFta05wvBnEjIQdUFaGcSXMGE1CN2PEo=
